[package]
name = "mod-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = { git = "https://github.com/serenity-rs/poise.git", rev = "fe2f25097166e1e7fb56f341cbad9a2bc771a931" }
# Be sure serenity is on commit `5746fadda4313ff00898ee8b13eadcf08dd89442` in
# `Cargo.lock`. At the time of writing, that's the latest commit compatible with
# poise.
